spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://uxllnyewecjioh:6c6ae6cc14c00728e9afbc5f7c8beaf5d7d861efa129b77163fa0f930317854c@ec2-44-198-215-235.compute-1.amazonaws.com:5432/d1uofst5qs8ove
    username: uxllnyewecjioh
    password: 6c6ae6cc14c00728e9afbc5f7c8beaf5d7d861efa129b77163fa0f930317854c

server:
  port: 8080

app:
  execute:
    user: テストユーザー
  google:
    oauth2-url: https://www.googleapis.com/oauth2/v4/token
    api-url: https://sheets.googleapis.com/v4/spreadsheets/
    sheet-id: 13RqLVAYKnbff6f5cWPzqyh-1y5j8NC_brqI_Le73qhI
    client-id: 455165694555-gekiq4j8upinbq5kejusq7t92r7t560v.apps.googleusercontent.com
    client-secret: 6r7S3FqjssNuXM8FbKa-GLX0
    refresh-token: 1//0eUMWJyOCHBimCgYIARAAGA4SNwF-L9IrbwgtJYYyS1qfAi-0l2d_LjZaK1Cth6FbicCFBEeoJjc8rVdHHM5sye1xQDDuv7KHDic
